#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2021 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: Unlicense

# Exit immediately on each error and unset variable;
# see: https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -Eeuo pipefail
#set -Eeu

script_dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")

JENA_VERSION="4.2.0"
JENA_DL_URL="https://dlcdn.apache.org/jena/binaries/apache-jena-$JENA_VERSION.zip"
JENA_FUSEKI_DL_URL="https://dlcdn.apache.org/jena/binaries/apache-jena-fuseki-$JENA_VERSION.zip"

# For the DB
JENA_HOME="$HOME/.local/opt/apache-jena-$JENA_VERSION"
# For the (SPQRQL) query web interface ot the DB
JENA_FUSEKI_HOME="$HOME/.local/opt/apache-jena-fuseki-$JENA_VERSION"

# This dir is where our RDF data will be stored (in a query-efficient way)
db_dir="$script_dir/rdf_db"
jena_db_data_injector="$JENA_HOME/bin/tdb2.tdbloader"
jena_db_data_querier="$JENA_HOME/bin/tdb2.tdbquery"
jena_fuseki_server="$JENA_FUSEKI_HOME/fuseki-server"

function ensure_tool() {
	home="$1"
	url="$2"
	name="$3"

	echo
	printf 'Checking %s is available ... ' "$name"
	if [ -d "$home" ]
	then
		echo "yes!"
	else
		echo "no,"
		echo "installing it under $home ..."
		mkdir -p "$home"
		rm -Rf "${home:?}"
		archive_name="$(basename "$url")"
		dir_name="${archive_name%.zip}"
		wget "$url"
		unzip "$archive_name"
		mv "$dir_name" "$home"
		rm "$archive_name"
		echo "done."
	fi
}

