# SPDX-FileCopyrightText: 2025 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: Unlicense

PREFIX okh: <http://w3id.org/oseg/ont/okh#>

# Count all projects (aka modules)
SELECT (COUNT(*) AS ?count)
WHERE {
  ?proj a okh:Module
}
