# SPDX-FileCopyrightText: 2025 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: Unlicense

PREFIX ods: <http://w3id.org/oseg/ont/ods#>
PREFIX okh: <http://w3id.org/oseg/ont/okh#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX otrl: <http://w3id.org/oseg/ont/otrl#>
PREFIX spdxt: <http://spdx.org/rdf/terms#>

# All projects with a specific license
SELECT ?subj ?name ?license
WHERE {
  ?subj a okh:Module .
  ?subj okh:name ?name .
  ?subj ods:license ?license .
  ?subj ods:license spdxt:CC-BY-SA-3.0
  #?subj ods:license spdxt:CC-BY-SA-4.0
  #?subj ods:license spdxt:GPL-3.0-or-later
  #?subj ods:license spdxt:Unlicense
  #?subj ods:license spdxt:CC0-1.0
  #?subj ods:license spdxt:Apache-2.0
}
LIMIT 100
