#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2021 - 2024 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: Unlicense

# See the output of "$0 -h" for details.

# Exit immediately on each error and unset variable;
# see: https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -Eeuo pipefail
#set -Eeu

script_path="$(readlink -f "${BASH_SOURCE[0]}")"
script_dir="$(dirname "$script_path")"
# shellcheck source=./_common
source "$script_dir/_common"
script_name="$(basename "$(readlink -f "${BASH_SOURCE[0]}")")"

# initial default values
APP_NAME="RDF DB Filler"
CLONE_URL_OKH_ONTOLOGY="https://github.com/iop-alliance/OpenKnowHow.git"
CLONE_URL_OLD_DATA="https://gitlab.opensourceecology.de/verein/projekte/okh/data.git"
CLONE_URL_EXP_DATA="git@github.com:OSEGermany/OKH-data-experimental.git"
data_url="$CLONE_URL_OLD_DATA"
data_branch="main"
cleanup=false
online=true

function print_help() {

	echo "$APP_NAME - Fills an Apache Jena RDF DB with data from RDF/Turtle files."
	echo
	echo "Usage:"
	echo "  $script_name [OPTION...]"
	echo "Options:"
	echo "  -h, --help"
	echo "    Print this usage help and exit"
	echo "  --offline"
	echo "    Do not try to fetch git repos"
	echo "  --experimental"
	echo "    Uses the new experimental data source"
	echo "    NOTE: This data is private, so you need to get access first"
	echo "  --custom-data <GIT-REPO-URL> <BRANCH>"
	echo "    Uses the given git reoo and branch as the data-source"
	echo "    Please use an HTTP(S) git URL without the need for authentification."
	echo "Examples:"
	echo "  $script_name"
	echo "  $script_name --help"
	echo "  $script_name --experimental"
	echo "  $script_name --custom-data \"$CLONE_URL_OLD_DATA\" main"
}

# read command-line args
POSITIONAL=()
while [[ $# -gt 0 ]]
do
	arg="$1"
	shift # $2 -> $1, $3 -> $2, ...

	case "$arg" in
		-h|--help)
			print_help
			exit 0
			;;
		-o|--offline)
			online=false
			;;
		--experimental)
			data_url="$CLONE_URL_EXP_DATA"
			;;
		--custom-data)
			data_url="$1"
			shift
			data_branch="$1"
			shift
			;;
		*) # non-/unknown option
			POSITIONAL+=("$arg") # save it in an array for later
			;;
	esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters

function repo_ensure_latest() {
	dir="$1"
	clone_url="$2"
	main_branch="${3:-master}"
	if [ -d "$dir" ]
	then
		if $online
		then
			git -C "$dir" fetch origin "$main_branch"
			git -C "$dir" rebase "origin/$main_branch"
		fi
	else
		if ! $online
		then
			>&2 echo "ERROR: --offline chosen and repo '$dir' not present!"
			exit 1
		fi
		git clone "$clone_url" --single-branch "$dir"
	fi
}

ensure_java_version
ensure_tool "$JENA_HOME" "$JENA_DL_URL" "Apache Jena"

mkdir -p "$build_dir"
mkdir -p "$data_dir"

echo
echo "Get/Update input RDF ..."

ont_dir_name="$(basename --suffix ".git" "$CLONE_URL_OKH_ONTOLOGY")"
ont_dir="$data_dir/$ont_dir_name"
repo_ensure_latest "$ont_dir" "$CLONE_URL_OKH_ONTOLOGY"
ontology_ttls_root="$ont_dir/src/spec"

data_slug_parent="$(basename "$(dirname "$data_url")")"
data_slug_repo="$(basename --suffix ".git" "$data_url")"
data_dir_name="${data_slug_parent}__$data_slug_repo"
projs_data_dir="$data_dir/$data_dir_name"
repo_ensure_latest "$projs_data_dir" "$data_url" "$data_branch"
data_ttls_root="$projs_data_dir"

if $cleanup
then
	echo
	echo "Checking file-names ..."
	find \
		"$data_ttls_root" -type f -name "*.ttl" \
		| while read -r file
	do
		no_spaces_file="${file// /_}"

		if [ "$no_spaces_file" != "$file" ]
		then
			>&2 echo "ERROR: File-name with spaces detected, please rename: '$file'"
			exit 2
		fi
	done

	echo
	echo "Fixing the data from the Krawler ..."
	find \
		"$data_ttls_root" -type f -name "*.ttl" \
		-name "*.ttl" \
		| while read -r ttl_file
	do
		echo "    '$ttl_file' ..."
		sed -i \
			-e 's|^@base\(.*\)#> .$|@base\1> .\n@prefix :         <#> .|' \
			"$ttl_file"
	done
fi

tmp_db_dir="${db_dir}_tmp"
bak_db_dir="${db_dir}_bak"

echo
echo "Setting up the DB in '$db_dir' (temp dir: '$tmp_db_dir') ..."

rm -Rf "$tmp_db_dir"
mkdir -p "$tmp_db_dir"
time find \
	"$ontology_ttls_root" \
	"$data_ttls_root" \
	-name "*.ttl" \
	-print0 \
	| xargs -0 "$jena_db_data_injector" \
	--loc "$tmp_db_dir" \
	--syntax turtle
if [ -e "$db_dir" ]
then
	rm -Rf "$bak_db_dir"
	mv "$db_dir" "$bak_db_dir"
	echo "The old DB is now at '$bak_db_dir'."
fi
mv "$tmp_db_dir" "$db_dir"
echo "done. (Setting up the DB)"

echo
echo "Ready to run SPARQL queries!"
echo
echo "for example:"
echo "$jena_db_data_querier \\"
echo "    --loc \"$db_dir\" \\"
echo "    --query \"$res_dir/sample-query.txt\""
echo
echo "Or start the Web interface for running SPARQL queries with:"
echo "run/web-ui"
