#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2024 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: Unlicense

# See the output of "$0 -h" for details.

# Exit immediately on each error and unset variable;
# see: https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -Eeuo pipefail
#set -Eeu

script_path="$(readlink -f "${BASH_SOURCE[0]}")"
script_dir="$(dirname "$script_path")"
# shellcheck source=./_common
source "$script_dir/_common"
script_name="$(basename "$(readlink -f "${BASH_SOURCE[0]}")")"

# initial default values
APP_NAME="RDF DB Dependencies Installer"

function print_help() {

	echo "$APP_NAME - Installs all the dependencies."
	echo
	echo "Usage:"
	echo "  $script_name [OPTION...] [DEPENDENCY...]"
	echo "Options:"
	echo "  -h, --help"
	echo "    Print this usage help and exit"
	echo "Examples:"
	echo "  $script_name"
	echo "  $script_name --help"
}

# read command-line args
POSITIONAL=()
while [[ $# -gt 0 ]]
do
	arg="$1"
	shift # $2 -> $1, $3 -> $2, ...

	case "$arg" in
		-h|--help)
			print_help
			exit 0
			;;
		*) # non-/unknown option
			POSITIONAL+=("$arg") # save it in an array for later
			;;
	esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters

ensure_java_version
ensure_tool "$JENA_HOME" "$JENA_DL_URL" "Apache Jena"
ensure_tool "$JENA_FUSEKI_HOME" "$JENA_FUSEKI_DL_URL" "Apache Jena Fuseki"
